/*
 *  Rapfi, a Gomoku/Renju playing engine supporting piskvork protocol.
 *  Copyright (C) 2022  Rapfi developers
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "../core/pos.h"
#include "../core/types.h"

#include <algorithm>
#include <cassert>
#include <memory>
#include <utility>
#include <variant>
#include <vector>

namespace Tuning {

/// Result represents the outcome of a finished game (based on current side to move).
/// Point-of-view conventions across the data pipeline (convert with flipResult):
///   - DataEntry::result is from the entry's side to move.
///   - GameEntry::result is from white's point of view.
///   - The binpack wire result is from the first mover of the move sequence.
enum Result : uint8_t { RESULT_LOSS, RESULT_DRAW, RESULT_WIN, RESULT_UNKNOWN };

/// The same outcome seen from the opponent's point of view.
constexpr Result flipResult(Result result)
{
    return result == RESULT_UNKNOWN ? RESULT_UNKNOWN : Result(RESULT_WIN - result);
}

/// One move in the multi-pv.
struct PVMove
{
    Pos  move;
    Eval eval;
};

/// Dense float policy target of size [boardsize^2+1] (pass at the last index).
using PolicyArrayF32 = std::vector<float>;
/// Dense int16-quantized policy target of size [boardsize^2+1], scale 1/32767.
using PolicyArrayI16 = std::vector<int16_t>;
/// The EXTRA multi-pv moves and evaluations (the best move is not included).
using ExtraPVArray = std::vector<PVMove>;

/// MovePayload is the optional per-move training payload attached to an entry.
/// Both an empty vector alternative and monostate mean "no payload": readers
/// reset a reused payload with clearPayload(), which empties the held vector
/// in place instead of switching to monostate, so the vector's capacity is
/// reused across entries in streaming loops (no steady-state allocations).
using MovePayload =
    std::variant<std::monostate, PolicyArrayF32, PolicyArrayI16, ExtraPVArray>;

/// Reset a payload to "no payload" without discarding allocated capacity.
inline void clearPayload(MovePayload &payload)
{
    std::visit(
        [](auto &v) {
            if constexpr (!std::is_same_v<std::decay_t<decltype(v)>, std::monostate>)
                v.clear();
        },
        payload);
}

/// Whether the payload holds any data (an empty vector counts as no payload).
inline bool hasPayload(const MovePayload &payload)
{
    return std::visit(
        [](const auto &v) {
            if constexpr (std::is_same_v<std::decay_t<decltype(v)>, std::monostate>)
                return false;
            else
                return !v.empty();
        },
        payload);
}

/// Get the held vector alternative of a reused payload for refilling: keeps the
/// current alternative (cleared, capacity preserved) if it already matches,
/// otherwise switches to an empty vector of the requested type.
template <typename VectorT>
inline VectorT &payloadAs(MovePayload &payload)
{
    if (auto *v = std::get_if<VectorT>(&payload)) {
        v->clear();
        return *v;
    }
    return payload.emplace<VectorT>();
}

/// The extra multi-pv list of a payload, or nullptr if it holds none.
inline const ExtraPVArray *extraPVs(const MovePayload &payload)
{
    auto *pvs = std::get_if<ExtraPVArray>(&payload);
    return pvs && !pvs->empty() ? pvs : nullptr;
}

/// The policy target of one move for cell `pos`, from its payload. If no dense
/// policy target is available, all policy is concentrated on the best move.
inline float policyTargetOf(const MovePayload &payload, Pos bestMove, int boardsize, Pos pos)
{
    size_t index = pos == Pos::PASS ? boardsize * boardsize : pos.y() * boardsize + pos.x();
    if (auto *p = std::get_if<PolicyArrayF32>(&payload); p && !p->empty())
        return (*p)[index];
    if (auto *p = std::get_if<PolicyArrayI16>(&payload); p && !p->empty())
        return (*p)[index] * (1.0f / 32767);
    return pos == bestMove ? 1.0f : 0.0f;
}

/// DataEntry struct represents a raw training data entry that generated by running
/// a match between two engines. It contains the complete position (represented as
/// a sequence of move played by each side), move outputed by the current side to move,
/// board size, rule, game outcome and an optional per-move payload (dense policy
/// target or extra multi-pv moves). All members have value semantics; entries copy,
/// move and destroy correctly with the compiler-generated special members.
/// Streaming contract: dataset readers refill a caller-supplied entry in place
/// (clearing, not shrinking, its buffers), so a reused entry reaches a steady state
/// with no per-entry allocations; its contents are valid until the next call.
struct DataEntry
{
    std::vector<Pos> position;   // move sequence that representing a position
    Pos              move;       // best move output by the engine
    Eval             eval;       // evaluation of the position (side to move pov)
    uint8_t          boardsize;  // size of a square board
    Rule             rule;       // rule of the game entry
    Result           result;     // game result: 0=loss, 1=draw, 2=win (side to move pov)
    MovePayload      payload;    // optional policy target / extra multi-pv moves

    DataEntry() = default;
    DataEntry(std::vector<Pos> pos,
              uint8_t          boardsize,
              Rule             rule,
              Result           result = RESULT_UNKNOWN,
              Pos              move   = Pos::NONE,
              Eval             eval   = VALUE_NONE)
        : position {std::move(pos)}
        , move(move)
        , eval(eval)
        , boardsize {boardsize}
        , rule {rule}
        , result {result}
    {}

    /// Returns the current side to move. Every move in `position` - pass moves
    /// included - yields the turn to the opponent, matching Board::move(Pos::PASS),
    /// the binpack reader and the Trainer-side reader.
    Color sideToMove() const { return position.size() % 2 == 0 ? BLACK : WHITE; }

    /// The number of extra multi-pv moves in the payload.
    int numExtraPVs() const
    {
        const ExtraPVArray *pvs = extraPVs(payload);
        return pvs ? (int)pvs->size() : 0;
    }

    /// Get policy target according to pos. If no dense policy target
    /// is available, all policy is concentrated on the best move pos.
    float policyTarget(Pos pos) const { return policyTargetOf(payload, move, boardsize, pos); }
};

/// GameEntry struct represents a complete training game that is generated by running
/// a selfplay match or a match between two engines. Positions of each data entry can
/// be acquired from the move sequence outputed by two engines.
struct GameEntry
{
    struct MoveData
    {
        Pos         move;     // best move output by the engine
        Eval        eval;     // evaluation of the position (side to move pov)
        MovePayload payload;  // optional policy target / extra multi-pv moves
    };

    std::vector<Pos>      initPosition;  // initial position of the game
    std::vector<MoveData> moveSequence;  // move data sequence that representing a game
    uint8_t               boardsize;     // size of a square board
    Rule                  rule;          // rule of the game entry
    Result                result;        // game result: 0=loss, 1=draw, 2=win (white pov)

    GameEntry()                           = default;
    GameEntry(GameEntry &&other) noexcept = default;
    GameEntry &operator=(GameEntry &&other) noexcept = default;
    /// Copying stays deleted on purpose: a game with per-move payloads can be
    /// megabytes, and no caller needs a deep copy. Move or pass by reference.
    GameEntry(const GameEntry &other)            = delete;
    GameEntry &operator=(const GameEntry &other) = delete;
};

}  // namespace Tuning
